lesson 5
nazip/turnIDE pull request #5
Opened 2017-02-16 11:38 UTC by nazip

Не смог разрешить все конфликты когда делал merge и  rebase  всех PR.
Поэтому перезалил весь проект заново.
Жду разгромной критики :)   (может научусь чему нибудь :)

2017-02-19 10:41 UTC, index01d requested changes
Запуск линтера
`./node_modules/eslint/bin/eslint.js src/.` возвращает 11 проблем, которые нужно исправить.

Название файла модуля (а также название самого компонента) должно начинаться с большой буквы;

Следует избегать относительных путей при импорте модуля.

2017-02-19 10:41 UTC, index01d commented on src/components/containers/blogPage.js
> +import BlogList from '../ui/blogList';
Вместо относительных путей лучше использовать абсолютные 
`import BlogList from 'components/ui/BlogList'`

2017-02-19 10:41 UTC, index01d commented on src/components/ui/metaData.js
> +    autor: 'not defined',
author

2017-02-19 10:41 UTC, index01d commented on src/components/ui/metaData.js
> +MetaData.propTypes = {
лучше описывать подробнее при помощи PropTypes.shape

2017-02-19 10:41 UTC, index01d commented on src/components/ui/textBox.js
> +const TextBox = ({txt = ''}) => (
лучше использовать children

2017-02-19 10:41 UTC, index01d commented on src/routes/index.js
> +  path: '/post/:id',
лучше реализовать метод-хелпер для конструирования запроса (как в уроке)

2017-02-19 10:41 UTC, index01d commented on src/components/post.js
> +              <BlogItem item={this.state.item[0]} likeHandler={() => ('')} />
зачем здесь передан likeHandler?

2017-02-19 10:41 UTC, index01d commented on src/components/containers/blogPage.js
> +      item.map((item) => {
item.map((item) => ...) ? Непонятно.

2017-02-19 10:41 UTC, index01d commented on src/components/containers/blogPage.js
> +        m.metadata.like = m.metadata.like + 1;
Неявное изменение содержимого состояния. см Мутабельность/Иммутабельность.

2017-02-19 10:41 UTC, index01d commented on src/components/containers/blogPage.js
> +    this.setState({items: newItem});
items - много newItem - один, вводит в некоторое заблуждение. Это конечно стилистическая придирка, но на мой взгляд важная.

2017-02-19 10:41 UTC, index01d commented on src/components/ui/blogList.js
> +    this.setState({activePage: name});
почему name?:)

2017-02-19 10:41 UTC, index01d commented on src/components/ui/blogList.js
> +  render() {
`const { activePage, itemsPerPage } = state;`, тогда строки ниже станут сильно короче

2017-02-19 10:41 UTC, index01d commented on src/components/ui/blogList.js
> +                     active={this.state.activePage === key.toString()}
почему activePage строка?

2017-02-19 10:41 UTC, index01d commented on src/components/ui/blogList.js
> +      {item.map((item, key) => {
items?

2017-02-19 10:41 UTC, index01d commented on src/components/ui/blogList.js
> +      <Menu pagination>
Компонент с пейджинацией лучше выделить как отдельный

2017-02-19 10:41 UTC, index01d commented on src/components/ui/blogList.js
> +        if ((key + 1 > this.state.activePage * this.state.itemsPerPage - this.state.itemsPerPage) &&
для взятия n элементов из массива можно пользоваться стандартной функцией slice (https://www.w3schools.com/jsref/jsref_slice_array.asp) Сделать это лучше перед вызовом map.

2017-02-21 10:49 UTC, nazip commented on src/components/containers/blogPage.js
> +      item.map((item) => {
перебираю вложенный массив (при запросе к серверу получаю вложенный массив item - ов)

2017-02-21 10:52 UTC, nazip commented on src/components/containers/blogPage.js
> +      item.map((item) => {
и далее в render() даю каждому BlogList подмассив

2017-02-21 18:51 UTC, index01d requested changes
Почему-то не везде изменены относительные пути на абсолютные.

Кроме того в ui намешаны компоненты с разным назначением (многие из них можно снести в elements/, например Image)

2017-02-21 18:52 UTC, index01d requested changes

2017-02-21 18:52 UTC, index01d commented on src/components/containers/BlogPage.js
> +    this.setState({items: item});
и все же почему в единственном числе item? должно же быть items?

2017-02-22 05:38 UTC, nazip commented on src/components/containers/BlogPage.js
> +    this.setState({items: item});
Если поставить item в множественном числе, то linter дает warning http://eslint.org/docs/rules/object-shorthand
Можно конечно написать : 
likeClick(id) {
    const newItems = this.state.items.map((item) => (
      item.map((item) => {
        if (item.id !== id) return item;
        const m = Object.assign({}, item);
        m.metadata.like += 1;
        return m;
      })
    ));
    this.setState({items: newItems});
  }
или есть более красивый вариант ?

2017-02-22 12:22 UTC, index01d commented on src/components/containers/BlogPage.js
> +    this.setState({items: item});
> Если поставить item в множественном числе, то linter дает warning http://eslint.org/docs/rules/object-shorthand

Линтер просто указывает на то, что в этом случае можно использовать сокращенный синтаксис и написать `this.setState({ items })` вместо `this.setState({ items: items })`

> Хотелось бы точто прояснить для себя: Абсолютные пути применяются всегда без исключений (даже если компонент находится в той же папке ?)

Относительные применяются только тогда, когда нет сомнений в том, что они не перестанут быть актуальными
Например
```
- views/
  - widgets/
  - - Card.js
  - NewsView.js
```
В данном случае можно подключить во вьюхе карточку по относительному пути (если мы предполагаем, что она никогда, даже потенциально, не будет реиспользована в других представлениях). У тебя же много случаев когда так подключается компонент, который потенциально переедет в какое-то другое место по причине того, что возникнет желание его реиспользовать.

> У меня нет четкого понимания какой компонент где должен лежать. В elements должны быть компоненты которые более близки к Html тегам ? или здесь другой принцип ?

отвечал на подобные вопросы здесь: http://connect.thinknetica.com/t/zanyatie-5-marshrutizacziya/3854/38?u=indevelope

2017-02-26 10:53 UTC, index01d approved these changes

2017-02-27 05:04 UTC, merged