Redux1
nazip/turnIDE pull request #6
Opened 2017-03-07 12:49 UTC by nazip

В компоненте BlogPage в state храню items, но при наличии store, 
items я могу получить из store тоже (store.getState). Может одного (store) достаточно ?     
(В контейнере при необходимости items вызывать везде store.getState. )

2017-03-07 14:16 UTC, index01d commented
> Другими словами: бедет ли правильно все данные черпать из store и не хранить в контейнерах 
Будет правильно. Неправильно будет делать как-то иначе:)

2017-03-07 15:04 UTC, nazip commented
Понял. Спасибо

2017-03-09 08:30 UTC, nazip commented
У меня в приложении (как и на видео к уроку) есть два state (post и posts). Когда я кликяю на лайк - обновляется только один из них. Надо ли синхронизировать оба state ? А может одного state достаточно ? Если иметь только один обьект, то при обращении за получением состояния через store.getState(), получим однозначное состояние обьекта. А сейчас получается что один обьект лежит в 2 местах. Наверное я что-то 'не догоняю'  :)  Проясни пожалуйста

2017-03-10 12:05 UTC, nazip commented
Ну посмотри мой 'бредовый blog'  ..... очень хочется чему нибудь научиться :)

2017-03-11 10:54 UTC, index01d commented
смотрю смотрю:)

2017-03-12 11:37 UTC, index01d requested changes
Возникло некоторое дублирование с функцией лайка. Начнем с такой правки: нужно вынести actionCreator'ы, связанные с лайком из модулей в общий модуль actions/Like.js.

В списке постов и на странице поста использовать один и тот же action. При этом запрос нужно сделать в actionCreator'е, а изменение состояния лучше перенести в обработку в reducer'e (1 action можно при этом обработать и в reducer'е списка и в reducer'е одного поста).

Альтернативное решение в жизни: вынести лайки в отдельный reducer. Это позволяет сделать возможность ставить лайки не только постам, но и другим сущностям и выделить их логику в отдельные сущности. Но в данном случае лучше обойтись простым путем, про который я написал выше.

2017-03-13 11:53 UTC, nazip commented
Похоже все сделал. Проверь пожалуйста.

2017-03-13 16:29 UTC, index01d requested changes
Получилось немного не так, как я ожидал.
Теперь используется 1 actionCreator, который тем не менее может сделать два типа action'ов. Предлагаю сделать один общий actionCreator addLike. В него при этом нужно передавать только идентификатор поста (вместо всего поста). Тогда не потребуется делать инкремент в actionCreator'е.

Возможна например схема:
actionCreator addLike является асинхронным и отправляет на выполнение следующую последовательность действий
LIKE_INCREMENT // в reducer'ах (posts и post) инкрементируется значение
LIKE_REQUEST // отправляется запрос на обновление данных на сервере
LIKE_SUCCESS // успешно синхронизировано с серверов

Тут также есть дилемма с API.  Можно иметь выделенный метод like, либо нужно тогда уже сразу сделать метод-actionCreator updatePost() (да, он уже есть, но почему бы ему тогда не стать унифицированным, принимать не только значение like и переехать в actions/Post), чтобы содержимое соответствовало истине.

Эти действия помогут сократить количество кода, сделать его более логичным и понятным (за счет того, что actionCreator'ы перестанут выполнять функцию reducer'a в той части, где инкрементируется значение и формируется контент для отправки)

2017-03-13 16:39 UTC, index01d commented
Чтобы было понятнее, я лучше с нуля распишу последовательности того, как это должно работать

1. есть общий actionCreator addLike. В качестве аргумента он получает идентификатор поста и является асинхронным (возвращает функцию, которая принимает в качестве параметра метод dispatch).
2. Внутри функции actionCreator'a сначала мы отправляем на обработку dispatch({  type: LIKE_INCREMENT, id: [идентификатор поста из аргумента] }). На этот action должны среагировать два reducer'a (posts и post), они должны найти пост с нужным идентификатором у себя и инкрементировать там like.
3. Следующим шагом в функции нужно просигнализировать о том, что мы делаем запрос (dispatch(...LIKE_REQUEST или UPDATE_POST_REQUEST...)). reducer'ы могут либо никак не среагировать на это, либо выставить специальный флаг, который указывает на то, что идет синхронизация лайка с сервером, чтобы например крутить лоадером на кнопке
4. Далее необходимо инициировать запрос и по итогам задиспатчить либо _SUCCESS либо _ERROR

2017-03-13 16:53 UTC, index01d commented
Притом хочу еще заметить, что в реальной жизни такой способ установки like (через метод update с отправкой итогового количества) конечно неправильный, потому как одновременные запросы с клиентов приведут к потере правильного количества лайков и процесс будет очень неперсистентный. Верно все-таки было бы сделать отдельный rest-метод like, который выполнял бы инкремент на сервере и возвращал объект поста или итоговое количество лайков. Тогда количество действий вообще сократится до
LIKE_REQUEST // отправка запроса, здесь можно оптимистично в reducer'е инкрементировать значение, чтобы оно сразу применилось
LIKE_SUCCESS // получение ответа от сервера, применение количества лайков при обработке в двух reducer'ах
LIKE_ERROR // получение ответа от сервера, отмена оптимистично сделанного инкремента

2017-03-13 16:54 UTC, index01d commented
Написал много. Не стесняйся задавать вопросы, если что-то непонятно:)

2017-03-14 04:41 UTC, nazip commented
Спасибо за такой развернутый комментарий. Пока из всего что написано непонятного нет. Но думаю только пока :)

2017-03-14 09:23 UTC, nazip commented
поправил. Сделал новый action, который по id поста инкрементит лайк и возвращает этот обновленнй пост. Затем, когда ко мне прилетел пост я обновляю state для post и posts через dispatch (без запроса к БД). Можно конечно вернуть все посты с сервера после лайка на каком либо посте, но тут возникает делема между актуальностью информации на фронт энде и загрузкой сервера и БД  соответственно. Хочется конечно вернуть с сервера все посты при лайке на одном из них - кодирования меньше :) Может есть какой нибудь другой вариант ? Еще есть сомнения по отправки акшенов из других акшенов (это нормальная практика ? ). Это я про  setLike в /actions/Like.js
Жду вердикта :)

2017-03-14 10:58 UTC, nazip commented
Сделал action для лайка. 
Когда активен (виден в браузере)  компонент для одного поста, то обновляю только состояние для одного поста.
Когда активны (видны) несколько постов, то обновляю только состояние для всех постов.
При такой логике работы  меньше обращений  к серверу.
Или надо всегда иметь в состояниях актуальные значения для post и posts ?
Жду вердикта :)

2017-03-14 11:03 UTC, index01d commented
Если значение будет запрашиваться с сервера при переходе по страницам, то вполне нормально.

2017-03-14 11:04 UTC, index01d approved these changes

2017-03-14 11:04 UTC, index01d commented
дал прув, делай следующее ДЗ, там продолжим наше путешествие по коду:)

2017-03-14 12:19 UTC, merged