Redux2
nazip/turnIDE pull request #7
Opened 2017-03-20 11:04 UTC by nazip

Отключил Chart, иначе все посты  из БД придется считывать (при pagination  читаю из БД только одну страницу ). Или нужно было оставить chart сформированный для данных одной страницы ? :)

2017-03-21 18:10 UTC, index01d requested changes

2017-03-21 18:10 UTC, index01d commented on src/components/redux/actions/Like.js
> +      endpoint: `/post/like?id=${id}`,
параметр нужно унести в query

2017-03-21 18:10 UTC, index01d commented on src/components/containers/BlogList.js
> +    if (isFetching) {
длинную функцию render лучше декомпозировать на два компонента

2017-03-21 18:10 UTC, index01d commented on src/components/containers/BlogList.js
> +    if (isFetching) {
и возможно даже разнести вместе с этим логику

2017-03-21 18:10 UTC, index01d commented on src/components/redux/reducers/Posts.js
> +    case type.POSTS_PAGESIZE:
не совсем говорящее название, может переименовать в SET_PAGINATION_[INFO,PARAMS,-]?

2017-03-21 18:10 UTC, index01d commented on src/containers/PostsContainer.js
> +        dispatch(fetchPosts(store.getState().posts.pagination.activePage,
обычно бывает лучше (читаемее) выделить переменную с повторяющейся частью (store.getState().posts.pagination) и далее оперировать с ней. Также возможно стоит подписаться на результат выполнения dispatch(fetchPosts...).then(() => { здесь уже диспатчить смену активной страницы }), чтобы результат выглядел согласованным.
Последнее впрочем можно не делать, это уже вкусовщина.

2017-03-22 09:54 UTC, nazip commented
Все поправил.. гложет сомнения о необходимости обьединения обьектов Post и Posts в store. Вроде как дублирование данных происходит и структура данных одинакова (почти). Что скажешь ?

2017-03-22 14:50 UTC, index01d commented
скажу что на практике лучше держать их по разные стороны

2017-03-23 05:13 UTC, nazip commented
А что по проекту, есть что поправить ?

2017-03-25 08:33 UTC, nazip commented
Ну проверь уж побыстрей ...

2017-03-27 08:21 UTC, index01d requested changes

2017-03-27 08:21 UTC, index01d commented on src/components/containers/BlogList.js
> +      return <WaitingFor img={'/assets/images/wireframe/short-paragraph.png'}/>;
можно было и картинку тогда уж унести в целом:)) ну или завести идентификатор картинки (их же в любом случае будет ограниченное количество)

2017-03-27 08:21 UTC, index01d commented on src/components/redux/reducers/Posts.js
> +    case type.SET_PAGINATION_PAGESIZE:
почему бы не просто SET_PAGESIZE ?

2017-03-27 08:21 UTC, index01d commented on src/containers/PostsContainer.js
> +          newPageSize + pagination.pageSize > 0 ?
max(newPageSize + pagination.pageSize, 1)

2017-03-27 08:21 UTC, index01d commented on src/components/redux/reducers/Posts.js
> +          pageSize: action.pageSize > 0 ? action.pageSize : 1,
дублирует логику ниже

2017-03-27 08:21 UTC, index01d commented on src/containers/PostsContainer.js
> +          newPageSize + pagination.pageSize > 0 ?
дублирует теперь логику из reducer'a

2017-03-27 08:21 UTC, index01d commented
оу, извиняюсь. забыл нажать кнопку

2017-03-27 10:05 UTC, nazip commented
Все поправил :)  Посмотри

2017-03-27 10:42 UTC, nazip commented
Пытался использовать shouldComponentUpdate для того чтобы при лайке не рендерились все item, а только тот на котором лайкнули. Если не сложно подскажи где 'промахнулся' (пробовал в тело функции  ставить return false все равно компонент в упор не видит эту функцию )

`class BlogItem extends React.Component {

  shouldComponentUpdate(nextProps, nextState) {
    return this.props.item.metadata.like !==
      nextProps.item.metadata.like;
  }
  
  render() {
    const {image, metadata, id, txt} = this.props.item;
    console.log('id=', id);
      return  <Grid columns={2} divided>
                  <Grid.Row>
                    <Grid.Column>
                      <Header size='medium'><Link to={postsPath(id)}>
                        {txt}</Link>
                      </Header>
                      <MetaData metadata={metadata} />
                      <Like like={metadata.like}
                      likeHandler={() => this.props.likeHandler(id)}/>
                    </Grid.Column>
                    <Grid.Column>
                      <Img img={image} />
                    </Grid.Column>
                  </Grid.Row>
                  <Divider/>
              </Grid>;
  }
}
`

2017-03-27 11:04 UTC, index01d approved these changes

2017-03-27 11:04 UTC, index01d commented on src/components/redux/const/actionTypes/Posts.js
> +export const SET_PAGESIZE = 'SET_PAGESIZE';
я бы может даже объединил тогда два этих метода

2017-03-27 11:04 UTC, index01d commented on src/containers/PostsContainer.js
> +            pageSize: -1 * newPageSize}));
желательно бы конечно, чтобы тут не было никаких расчетов. Все расчеты по хорошему должны вестись в reducer'e

2017-03-27 11:06 UTC, index01d commented
а как ты определяешь, что компонент не видит функцию? возможно, ты имеешь ввиду, что выводится console.log в render. В этом случае имеет смысл бросить лог в componentDidMount, тк возможно компонент вообще не обновляется, а монтируется заново всякий раз.

2017-03-27 13:26 UTC, nazip commented on src/components/redux/const/actionTypes/Posts.js
> +export const SET_PAGESIZE = 'SET_PAGESIZE';
Обьеденил,  возвращаю pagesize и  activepage  из api.

2017-03-27 13:26 UTC, nazip commented on src/containers/PostsContainer.js
> +            pageSize: -1 * newPageSize}));
переместил расчет в редьюсер

2017-03-27 13:33 UTC, nazip commented
По поводу componentDidMount:  ты конечно был прав  :)) (компонет монтируется каждый раз заново)

2017-03-29 18:26 UTC, index01d commented
больше не монтируется заново?

2017-03-29 18:52 UTC, nazip commented
Я пытался при 'лайке' в BlogItem  компоненте обновлять только один блог на текущей странице. Как ты и писал ранее я повесил console.log на render компонента BlogItem и shouldComponentUpdate все равно не блокировал render (даже если shouldComponentUpdate возвращал false).
Это происходило потому что контейнер BlogList 'чуял' изменение state и перересовывал все  BlogItem (т е монтировал все заново)  :)))  
Сейчас пробую решить свою проблему ( просто интересно )  при помощи создания отдельного редьюсера для лайков и через connect подключить часть state (лайки ) компоненту blogItem.
Даже не знаю на правильном пути я или нет ... Что скажешь ?

2017-03-29 21:19 UTC, index01d commented
больше не монтируется заново?

2017-03-29 21:20 UTC, index01d commented
пока не до конца вкурил твою ситуацию, завтра склонирую и посмотрю:))

2017-03-30 13:32 UTC, index01d commented
подскажи, где твой сервер забрать?

2017-03-30 13:42 UTC, nazip commented
https://github.com/nazip/apiForReact

2017-03-31 23:04 UTC, index01d commented
Наконец-то все развернул и посмотрел. Ну прямо сейчас все просто. Перерисовка происходит на общем списке из-за того, что в компоненте BlogList в случае isFetching возвращается другой элемент и демонтируется список до момента получения данных. isFetching устанавливается в true при запросе на постановку Like, что не совсем верно (поидее желательно иметь для каждого поста иметь флажок постановки лайка и реагировать на это внутри лайка, тогда лайк будет похож на фейсбуковый)

2017-03-31 23:05 UTC, index01d commented
я вижу, что ты уже пошел по этому пути. Важное замечание: лучше тогда дать Like-компоненту отдельный контейнер, тогда не придется пробрасывать handler через полпроекта(BlogItem), вместо этого можно будет использовать LikeContainer в BlogItem.

2017-03-31 23:06 UTC, index01d commented
мигни как сделаешь и сделаем небольшое review по проекту:)

2017-04-04 19:08 UTC, nazip commented
Посмотри на мое безобразие ... похоже сделал :)

2017-04-05 18:23 UTC, nazip commented
;)

2017-04-06 05:51 UTC, nazip commented
Ты куда пропал ? :)

2017-04-06 07:32 UTC, index01d commented
не пропал

2017-04-06 07:36 UTC, index01d commented
Сегодня запубликую ответ, я его еще формирую:)

2017-04-06 15:30 UTC, index01d requested changes
в целом почти развязали клубок:) Предлагаю выделить LikeContainer и загнать в него всю логику с выставлением значения количества лайков и обработку постановки лайка. Идентификатор поста можно передавать в свойстве id, и принимать в ownProps методов stateToProps и actionsToProps данного контейнера.
Тогда в BlogItem можно будет использовать
```
<LikeContainer id={item.id} />
```
Рекомендую делать более содержательные комментарии к коммитам, . Еще в код попало некое обновление семантика, которое заняло солидную часть PR'a и затруднило работу с ним.

P.S: Да, увидел лайкконтейнер над BlogItem, но это не то, что я имел ввиду. Я имел ввиду создать контейнер для кнопки Like'a и использовать его в BlogItem. То есть сделать нечто типа `connect(stateToProps, actionsToProps)(Like)`.

Если будет не ясно, то спрашивай, постараюсь объяснить идею нагляднее.

2017-04-06 15:30 UTC, index01d commented on src/routes/Blog.js
> +    store.dispatch(
1) можно деструктурировать настройки пейджинации заранее, чтобы не дублировать длинную строку параметров.
2) Не ясно откуда настройки возьмутся в состоянии (разве что в начальном состоянии). Лучше загнать их в константы и брать здесь их из get-параметров

2017-04-06 15:30 UTC, index01d commented on src/routes/Blog.js
>    prepareData: (store) => {
можно добавить здесь прием второго параметра – query, и брать настройки пейджинации из него с дефолтным значением из констант

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +// const getLike = (id) => (
закомментированный код в репозитории == очень плохо

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +    const {image, metadata, id, txt} = this.props.item;
можно деструктурировать здесь и все остальное
const { likes, like, item: { image, metadata, id, txt } } = this.props;

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +                      <Header size='medium'><Link to={postsPath(id)}>
ссылку для item лучше подготовить в контейнерном компоненте и сюда передавать уже готовую, тогда презентационный компонент не будет знать о роутерной логике

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +    const {image, metadata, id, txt} = this.props.item;
тогда ниже не придется делать длинную строку this.props.нечто

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +  shouldComponentUpdate(nextProps) {
непонятно назначение в данном компоненте.

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +  getLike(likes, id) {
не совсем ясно назначение метода. Если указывает на то, был ли установлен лайк или возвращает их количество, то эта проверка должна быть в контейнерном компоненте.

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +  getLike(likes, id) {
итоговое значение должно передаваться в параметре item'a

2017-04-06 15:30 UTC, index01d commented on src/components/views/Post.js
> +                likeHandler={(id) => like(id)}/>
лучше добавить LikeContainer, который будет мэпить в actionsToProps обработчик под ключом onClick, тогда BlogItem'у не нужно будет отвечать за логику постановки лайка

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +                      <Like like={this.getLike(this.props.likes, id)}
Здесь можно использовать созданный LikeContainer (ниже черкнул в комментарии)

2017-04-06 15:30 UTC, index01d commented on src/components/ui/BlogItem.js
> +  shouldComponentUpdate(nextProps) {
если убрать, то компонент станет stateless

2017-04-08 18:46 UTC, nazip commented
Посмотри, похоже поправил.

2017-04-08 19:13 UTC, index01d commented
Нет, я имел ввиду что можно же прямо здесь: https://github.com/nazip/turnIDE/blob/redux2/src/containers/PostsContainer.js пробежать по item'ам и проставить url каждому

2017-04-08 19:13 UTC, index01d commented
Приходи завтра на вебинар, как раз буду эти частовстречаемые неточности разбирать:)

2017-04-08 19:31 UTC, nazip commented
Про url понял.:)  спасибо

2017-04-08 21:05 UTC, index01d approved these changes
Принимаю, наведи там марафет где можно:) двигаем дальше. На вебинар все равно приходи, у меня целый сборник проблем заготовлен на обсуждение.

2017-04-10 08:30 UTC, merged