Forms
nazip/turnIDE pull request #9
Opened 2017-04-27 12:06 UTC by nazip

При добавлении нового комента, во вьюхе post, сразу не видно нового комента. Как ты думаешь может быть стоит обьеденить (т.е. сделать одну компоненту ) вместо BlogItem и Post ?

2017-04-28 07:27 UTC, index01d requested changes

2017-04-28 07:27 UTC, index01d commented on src/components/ui/Comments.js
> +  const commentsArray = Array.isArray(comments) ? comments : comments(id);
вот сюда должно всегда приходить одинаково, этой проверки быть не должно

2017-04-28 07:27 UTC, index01d commented on src/containers/CommentsContainer.js
> +    comments: (id) => state.posts.comments.filter(
здесь никогда не должно быть функции

2017-04-28 07:27 UTC, index01d commented on src/containers/CommentsContainer.js
> +const stateToProps = (state) => (
здесь нужно принять вторым параметром ownProps

2017-04-28 07:27 UTC, index01d commented on src/containers/CommentsContainer.js
> +    comments: (id) => state.posts.comments.filter(
должно быть просто
```
comments: filter(state.posts.comments, { id: ownProps.id }
```

а на месте использования `<CommentsContainer id={post.id} />`

2017-04-28 07:28 UTC, index01d commented
> Создал 2 контейнера для компонента Comments. Это нормальная практика или это мой очередной антипатент ?

Ничего особо плохого в этом нет. Правда выглядят эти контейнеры немного избыточно, но с заделом на будущее (они будут актуальны, когда помимо stateToProps в них будет actionsToProps с методами для отправки комментария и лайков, например).

2017-04-28 07:31 UTC, index01d commented
объединять BlogItem и Post не стоит, так как сейчас у них очень четко разделена зона ответственности. Возможно можно было бы только переименовать Post -> PostView/PostPage, для того чтобы суть ответственности прямо исходила из названия модуля. Но уже чисто стилистика

2017-04-28 11:13 UTC, nazip commented
Поправил контейнеры LikeContainer и CommentsContainer (убрал из stateToProps функции) Код стал опрятнее :) Посмотри что получилось 
P.S. Сейчас пытаюсь разбудить в себе дизайнера :)))  ... спит 'гад'... а ведь давно пора, весна уже давно на дворе :)

2017-05-03 18:29 UTC, nazip commented
пытался использовать react-dropzone для апдейта изображения в блоге. В акшене back end (rails) получаю в параметрах  : Parameters: {"item"=>{"id"=>"1", "title"=>"1111112sdfk;lsdkld;sfk;lsdkf;sdk;flsdkf;lskdfsfsd;fs", "author"=>"nazip1", "img"=>{"preview"=>"blob:http://localhost:3001/62a19087-d3de-4da0-ae9d-3b384f2a8b9f"}}, "id"=>"1"}
Не знаю как забрать сам image в каталог с изображениями (рельсовский каталог) В принципе в params имеется ссылка на image (preview) ... наверное надо скачать как-то ... короче не знаю. Подскажи направление поиска.

2017-05-04 21:53 UTC, index01d commented
Для файлов нужно немного прокачать middleware и добавить туда условие
```
// Attach file
  if ((method == 'POST' ||  method == 'PUT') && attachment) {
    const formData = new FormData();
    formData.append(attachment.key, attachment.file);
    r = r.send(formData);
  }
```

таким образом action должен получиться такой:
```
{
  [API_CALL]: {
    // тут все как обычно, но файлы должны попасть в поле attachment
    attachment: { key: 'media', file: media},
    // ну и тут тоже как обычно может быть что-то еще
  }
}
```

например:
```

export function uploadMedia (mediableType, mediableId, media, position = 1) {
  return {
    [API_CALL]: {
      endpoint: `/posts/media`,
      method: 'POST',
      attachment: { key: 'media', file: media},
      query: { position },
      types: [
        types.UPLOAD_MEDIA_REQUEST,
        types.UPLOAD_MEDIA_SUCCESS,
        types.UPLOAD_MEDIA_FAILURE
      ]
    },
    data: {
      mediableType, mediableId
    }
  };
}
```

2017-05-04 21:55 UTC, index01d commented
ну и документация по formData, чтобы была понятна суть (очень подробно будем разбирать в advanced курсе): https://developer.mozilla.org/ru/docs/Web/API/FormData

2017-05-07 13:47 UTC, nazip commented
Так как  по formData материал будет в advanced курсе  Мне  на следующий урок переходить можно ?    
Хочу конечно добить этот upload добить до конца , но боюсь не успеть закончить курс вовремя :)(дидлаин 12 мая по моему )

2017-05-07 16:25 UTC, nazip commented
Не могу понять почему  в onSubmit (src/containers/form/EditBlogContainer.js) нет файла который я загрузил в uploadFile (те массив пустой), хотя в store файл есть. Подскажи пожалуйста в какую сторону смотреть. Может конечно забить на uploadFile и перейти к следующему уроку, задание я как бы уже выполнил ? ... но все равно хочется знать почему я не вижу файл в обьекте values

2017-05-07 20:02 UTC, nazip commented
решил проблему (использовал reducer.plugin из redux-form) ... но появилась другая проблема :)) В акшене поста (updatePost) не могу послать файл  в мидлвару черз параметр attachment (через payload все проходит и на баг енд прилетает). Подскажи где я опять 'косячу' ?

2017-05-08 09:59 UTC, index01d commented
я мог бы подсказать почему через атачмент не работает, если бы ты запостил сюда вариант с аттачментом:) а то я ж не могу знать как ты его реализуешь.

2017-05-08 09:59 UTC, index01d approved these changes

2017-05-08 10:48 UTC, nazip commented
вот мидлвара где пытаюсь поймать attachment (он всегда false)
function APICall({ endpoint, method, query, payload, attachment = false }) {
  return new Promise((resolve, reject) => {
    let r = request[method.toLowerCase()](`${API_ROOT}${endpoint}`);
    // if ((attachment) && (method.toLowerCase() == 'post') || 
    //    (method.toLowerCase() == 'put')) {
    //   const formData = new FormData();
    //   formData.append(payload.key, payload.file);
    //   r = r.send(formData);
    // }
    if (query)
      r.query(stringify(query));
    if (payload) {
      const formData = new FormData();
      formData.append(payload.key, payload.file);
      r = r.send(formData);
      // r = r.send(payload);
    }
    r.end((error, data) => (
      error ?
        reject(error)
      : resolve(data.body)
    ));
  });
}

вот action, который вызывает мидлвару указанную выше  
export function updatePost(item) {
  return {
    API_CALL: {
      endpoint: `/post/${item.id}.json`,
      method: 'put',
      query: {item},
      payload: {key: 'file', file: item.uploadFile[0]},
      // attachment: {key: 'file', file: item.uploadFile[0]},
      types: [
        types.POST_UPDATE_REQUEST,
        types.POST_UPDATE_SUCCESS,
        types.POST_UPDATE_ERROR
      ]
    }
  };
}

Когда отпрвляю файл через параметр payload (в акшене) - в мидлваре я его вижу,  а когда через параметр attachment - то нет (те всегда false)

2017-05-09 05:28 UTC, index01d commented
обращаю внимание что чуть ниже в middleware мы сами и вызываем API_CALL и нужно передавать attachment втч там

2017-05-09 05:29 UTC, index01d commented
https://github.com/nazip/turnIDE/blob/server_render/src/components/redux/middleware/API.js#L35

2017-05-09 11:20 UTC, nazip commented
Спасибо большое :)))  В следующий раз постараюсь быть внимательнее :)

2017-05-09 12:18 UTC, merged